const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });

const doc = {

    // ============================
    // Informasi API
    // ============================
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },

    // ============================
    // Konfigurasi Server
    // ============================
    host: "localhost:3000",
    basePath: "/",

    // Protocol yang digunakan
    schemes: ['http', 'https'],

    // Format request yang diterima
    consumes: ['application/json'],

    // Format response yang dikirim
    produces: ['application/json'],

    // ============================
    // JWT Bearer Authentication
    // ============================
    // Bagian ini memberi tahu Swagger
    // bahwa API menggunakan JWT Bearer Token.
    // Nantinya akan muncul tombol "Authorize"
    // sehingga token tidak perlu ditulis manual
    // pada setiap endpoint.
    components: {
        securitySchemes: {
            bearerAuth: {
                type: "http",
                scheme: "bearer",
                bearerFormat: "JWT" //optional
            }
        }
    }

};

// ============================
// Lokasi file output Swagger
// ============================
const outputFile = './swagger-output.json';

// File yang akan discan swagger-autogen
const endpointsFiles = ['./index.js'];

// Generate swagger-output.json
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {

    // Jalankan aplikasi Express
    require('./index');

});